# Generated by Django 3.2 on 2024-11-06 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.CharField(max_length=9, unique=True, verbose_name='User ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', validators=[my_auth.models.validate_image_size], verbose_name='User Image')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Balance')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='Email')),
                ('country_code', models.CharField(choices=[('Bangladesh', '+88'), ('India', '+91')], default='Bangladesh', max_length=20)),
                ('number', models.CharField(max_length=11, unique=True, verbose_name='Number')),
                ('first_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Last Name')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=15, null=True, verbose_name='State')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio')),
                ('account_type', models.CharField(choices=[('senior_manager', 'Senior Manager'), ('manager', 'Manager'), ('senior_team_leader', 'Senior Team Leader'), ('team_leader', 'Team Leader'), ('trainer', 'Trainer'), ('senior_teacher', 'Senior Teacher'), ('teacher', 'Teacher'), ('accounter', 'Accounter'), ('help-line', 'Help-Line'), ('user', 'User'), ('admin', 'Admin')], default='user', max_length=20)),
                ('role', models.CharField(choices=[('user', 'User'), ('sub_admin', 'Sub Admin'), ('admin', 'Admin')], default='user', max_length=20)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_block', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('referraled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Referred By')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_referred', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referral',
                'ordering': ['-date_referred'],
            },
        ),
    ]
