# Generated by Django 5.1.2 on 2024-10-23 16:43

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/', validators=[account.models.validate_image_size])),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('country_code', models.CharField(choices=[('BD', '+88'), ('IND', '+91')], default='+88', max_length=10)),
                ('number', models.CharField(max_length=11, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=15, null=True)),
                ('last_name', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('account_type', models.CharField(choices=[('STL', 'Senior Team Leader'), ('TL', 'Team Leader'), ('STEAM', 'Selling Team'), ('MT', 'Marketing Team'), ('QT', 'Qualification Team'), ('HL', 'Help-Line'), ('TR', 'Trainer'), ('ST', 'Senior Teacher'), ('TEACHER', 'Teacher'), ('PET', 'Photo Editing Teacher'), ('VET', 'Video Editing Teacher'), ('SMT', 'Social Marketing Teacher'), ('COUNSELLOR', 'Counsellor'), ('SC', 'Senior Counsellor'), ('SM', 'Senior Manager'), ('CM', 'Counsellor Manager'), ('MM', 'Marketing Manager'), ('ACCOUNTER', 'Accounter'), ('USER', 'User')], default='User', max_length=50)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('sub_admin', 'Sub Admin')], default='User', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
