# Generated by Django 5.1.2 on 2024-10-23 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('STL', 'Senior Team Leader'), ('TL', 'Team Leader'), ('STEAM', 'Selling Team'), ('MT', 'Marketing Team'), ('QT', 'Qualification Team'), ('HL', 'Help-Line'), ('TR', 'Trainer'), ('ST', 'Senior Teacher'), ('TEACHER', 'Teacher'), ('PET', 'Photo Editing Teacher'), ('VET', 'Video Editing Teacher'), ('SMT', 'Social Marketing Teacher'), ('COUNSELLOR', 'Counsellor'), ('SC', 'Senior Counsellor'), ('SM', 'Senior Manager'), ('CM', 'Counsellor Manager'), ('MM', 'Marketing Manager'), ('ACCOUNTER', 'Accounter'), ('USER', 'User'), ('ADMIN', 'Admin')], default='USER', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('sub_admin', 'Sub Admin')], default='USER', max_length=20),
        ),
    ]
