# Generated by Django 5.1.2 on 2024-10-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_referred_by_alter_user_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_received_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
