# Generated by Django 5.1.2 on 2024-10-24 11:33

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_has_received_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='images/default-avatar.png', null=True, upload_to='images/', validators=[account.models.validate_image_size]),
        ),
    ]
