# Generated by Django 5.1.2 on 2024-10-24 11:33

import global_futures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Register_Side_Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='images/logo.png', null=True, upload_to='login-register-side-bar/', validators=[global_futures.models.validate_image_size])),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('banner', models.ImageField(blank=True, default='images/about-page-defult-thumb.jpg', null=True, upload_to='login-register-side-bar/', validators=[global_futures.models.validate_image_size])),
            ],
            options={
                'verbose_name': 'Login/Register Sidebar',
                'verbose_name_plural': 'Login/Register Sidebar',
                'ordering': ['logo', 'title', 'banner'],
            },
        ),
    ]
