# Generated by Django 5.1.2 on 2024-10-31 04:47

import global_futures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_futures', '0002_contact_info_footer_bottom_menu_headermenu_logoimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfoFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterCopyRightText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterPaymentMethodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', validators=[global_futures.models.validate_image_size])),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', validators=[global_futures.models.validate_image_size])),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='footersection',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='footersection',
            name='footer_bottom_menu_list',
        ),
        migrations.RemoveField(
            model_name='headersection',
            name='menu_list',
        ),
        migrations.DeleteModel(
            name='Contact_Info',
        ),
        migrations.DeleteModel(
            name='Footer_Bottom_Menu',
        ),
        migrations.DeleteModel(
            name='FooterSection',
        ),
        migrations.DeleteModel(
            name='HeaderMenu',
        ),
        migrations.DeleteModel(
            name='HeaderSection',
        ),
    ]
