# Generated by Django 5.1.2 on 2024-10-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_futures', '0003_contactinfofooter_footercopyrighttext_footerlogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfofooter',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
