# Generated by Django 3.2 on 2024-11-06 09:06

from django.db import migrations, models
import global_feature.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/', validators=[global_feature.models.validate_image_size], verbose_name='Favicon Image')),
            ],
            options={
                'verbose_name': 'Favicon',
                'verbose_name_plural': 'Favicon',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LoginRegisterSideBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='images', validators=[global_feature.models.validate_image_size], verbose_name='banner Iamge')),
            ],
            options={
                'verbose_name': 'Login Register Side Bar',
                'verbose_name_plural': 'Login Register Side Bar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/', validators=[global_feature.models.validate_image_size], verbose_name='Logo Image')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo',
                'ordering': ['-id'],
            },
        ),
    ]
