# Generated by Django 3.2 on 2024-11-06 15:44

from django.db import migrations, models
import global_feature.models


class Migration(migrations.Migration):

    dependencies = [
        ('global_feature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfoFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Contact Info Footer',
                'verbose_name_plural': 'Contact Info Footer',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FooterCopyRightText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=200, null=True, verbose_name='Footer Copy Right Text')),
            ],
            options={
                'verbose_name': 'Footer Copy Right Text',
                'verbose_name_plural': 'Footer Copy Right Text',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FooterDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Short Description')),
            ],
            options={
                'verbose_name': 'Footer Description',
                'verbose_name_plural': 'Footer Description ',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FooterPaymentMethodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', validators=[global_feature.models.validate_image_size], verbose_name='Footer Payment Method Image')),
            ],
            options={
                'verbose_name': 'Footer Payment Method Image',
                'verbose_name_plural': 'Footer Payment Method Image',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/', validators=[global_feature.models.validate_image_size], verbose_name='Social Media Icon')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url Link')),
            ],
            options={
                'verbose_name': 'Social Media Icon',
                'verbose_name_plural': 'Social Media Icon',
                'ordering': ['-id'],
            },
        ),
    ]
