# Generated by Django 5.1.2 on 2024-10-27 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.withdrawalmethod')),
            ],
        ),
    ]
