# Generated by Django 5.1.2 on 2024-10-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='blogmodel',
            old_name='Categorys',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='blogmodel',
            old_name='Tags',
            new_name='tags',
        ),
    ]
