# Generated by Django 5.1.2 on 2024-10-31 01:27

import blogs_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_page', '0002_alter_blogmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(upload_to='blogs/', validators=[blogs_page.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(help_text='Enter the title of the blog post.', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
