# Generated by Django 5.1.2 on 2024-10-30 12:38

import django.core.validators
import home_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(blank=True, max_length=80, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', validators=[home_page.models.validate_image_size])),
            ],
        ),
        migrations.CreateModel(
            name='Help_Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_url', models.URLField(blank=True, null=True)),
                ('any_kind_of_problem_date', models.CharField(blank=True, max_length=50, null=True)),
                ('any_kind_of_problem_google_meeting_url', models.URLField(blank=True, null=True)),
                ('team_leader', models.CharField(blank=True, max_length=80, null=True)),
                ('team_leader_whatup_number', models.CharField(blank=True, max_length=15, null=True)),
                ('trainer', models.CharField(blank=True, max_length=80, null=True)),
                ('trainer_whatup_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Live_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_topic', models.CharField(blank=True, max_length=80, null=True)),
                ('joining_time', models.CharField(blank=True, max_length=50, null=True)),
                ('join_meeting_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Special_Fuature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', validators=[home_page.models.validate_image_size])),
                ('title', models.CharField(blank=True, max_length=35, null=True)),
                ('short_description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(250)])),
            ],
        ),
    ]
