# Generated by Django 3.2 on 2024-11-06 09:06

from django.db import migrations, models
import home_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/', validators=[home_page.models.validate_image_size], verbose_name='Achievement Icon')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievement',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AdminHelpLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Admin Whatsup Number')),
            ],
            options={
                'verbose_name': 'Admin Help Line',
                'verbose_name_plural': 'Admin Help Line',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Title')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', validators=[home_page.models.validate_image_size], verbose_name='Banner Image')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HelpLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_url', models.URLField(blank=True, null=True, verbose_name='Telegram Url')),
                ('any_kind_of_problem_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Problem Solveing Date')),
                ('any_kind_of_problem_google_meeting_url', models.URLField(blank=True, null=True, verbose_name='Problem Solving Google Meet Url')),
                ('team_leader', models.CharField(blank=True, max_length=80, null=True, verbose_name='Team Teader Name')),
                ('team_leader_whatup_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Team Leader Whatsup Number')),
                ('trainer', models.CharField(blank=True, max_length=80, null=True, verbose_name='Trainer Name')),
                ('trainer_whatup_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Trainer Whatsup Number')),
            ],
            options={
                'verbose_name': 'Help Line',
                'verbose_name_plural': 'Help Line',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_topic', models.CharField(blank=True, max_length=80, null=True, verbose_name='Class Topic')),
                ('joining_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='joining Time')),
                ('join_meeting_url', models.URLField(blank=True, null=True, verbose_name='Join Metting Url')),
            ],
            options={
                'verbose_name': 'Live Class',
                'verbose_name_plural': 'Live Class',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SpecialFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/', validators=[home_page.models.validate_image_size], verbose_name='Feature Image')),
                ('title', models.CharField(blank=True, max_length=80, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Special Feature',
                'verbose_name_plural': 'Special Feature',
                'ordering': ['-id'],
            },
        ),
    ]
