# Generated by Django 5.1.2 on 2024-10-30 23:11

import home_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', validators=[home_page.models.validate_image_size])),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('short_description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
